In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [3]:
data= pd.read_csv('abalone.csv')
data.head(5)

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [4]:
# pembagian data cara 1
le=LabelEncoder() 
data['Sex']=le.fit_transform(data['Sex'])
dataaray=np.asarray(data)
baris,kolom=dataaray.shape
kolom=kolom
atribute=dataaray[:,1:kolom]
target=dataaray[:,0]

In [5]:
# pembagian data cara 2
# le=LabelEncoder() 
# data['Sex']=le.fit_transform(data['Sex'])
# # dataaray=np.asarray(data)
# # baris,kolom=data.shape
# # kolom=kolom-1
# atribute=np.asarray(data.drop('Sex',axis=1))
# target=np.asarray(data['Sex'])

In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(atribute,target,test_size=0.50)

In [7]:
target

array([2., 2., 0., ..., 2., 0., 2.])

In [8]:
atribute

array([[ 0.455 ,  0.365 ,  0.095 , ...,  0.101 ,  0.15  , 15.    ],
       [ 0.35  ,  0.265 ,  0.09  , ...,  0.0485,  0.07  ,  7.    ],
       [ 0.53  ,  0.42  ,  0.135 , ...,  0.1415,  0.21  ,  9.    ],
       ...,
       [ 0.6   ,  0.475 ,  0.205 , ...,  0.2875,  0.308 ,  9.    ],
       [ 0.625 ,  0.485 ,  0.15  , ...,  0.261 ,  0.296 , 10.    ],
       [ 0.71  ,  0.555 ,  0.195 , ...,  0.3765,  0.495 , 12.    ]])

In [9]:
clf=Perceptron(tol=0.1,max_iter=500)
clf.fit(xtrain,ytrain)

Perceptron(max_iter=500, tol=0.1)

In [10]:
prediksi=clf.predict(xtest)

In [11]:
print(prediksi)
print(ytest)

print('sama = ' + str(np.array_equal(prediksi,ytest)))
print('Accuracy: %.2f' % accuracy_score(ytest, prediksi))

[0. 0. 0. ... 0. 0. 0.]
[2. 0. 1. ... 0. 2. 1.]
sama = False
Accuracy: 0.36
